=== readmeio/metrics-sdks/packages/ruby/spec/schema/payload.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string"
    },
    "group": {
      "$ref": "readmeGroup.json#"
    },
    "clientIPAddress": {
      "type": "string"
    },
    "development": {
      "type": "boolean"
    },
    "request": {
      "$ref": "har.json#"
    }
  },
  "required": ["group", "clientIPAddress", "development", "request"]
}

=== readmeio/metrics-sdks/json1.json
[
  {
    "development": false,
    "group": {
      "email": "johnsmithid012@gmail.com",
      "label": "JohnSmith",
      "id": "kiy5tLMfG2vTegvTzObjyuVqURHptTNG"
    },
    "request": {
      "log": {
        "creator": {
          "name": "readmeio",
          "version": "1.2.1",
          "comment": "mac/v10-16.0"
        },
        "entries": [
          {
            "request": {
              "headers": [
                {
                  "name": "host",
                  "value": "127.0.0.1:50799"
                }
              ],
              "queryString": [
                {
                  "name": "country",
                  "value": "usa"
                }
              ],
              "postData": {
              },
              "method": "GET",
              "url": "http://127.0.0.1:50799/test",
              "httpVersion": "HTTP/1.1"
            },
            "response": {
              "headers": [
                {
                  "name": "x-powered-by",
                  "value": "Express"
                }
              ],
              "content": {
                "text": "OK",
                "size": 2,
                "encoding": "utf-8"
              },
              "status": 200,
              "statusText": "OK"
            },
            "pageref": "http://127.0.0.1/test",
            "startedDateTime": "2021-10-22T20:54:04.150Z",
            "time": 4
          }
        ]
      }
    },
    "_id": "guid_id",
    "clientIPAddress": "127.0.0.1"
  }
]
